#################################################################
###################### NexT Configuration #######################
#################################################################

# ============================================================= #
# ============= Theme Core Configuration Settings ============= #
# ============================================================= #

custom_file_path:
  sidebar: source/_data/sidebar.njk
  footer: source/_data/footer.njk
  variable: source/_data/variables.styl
  style: source/_data/styles.styl


# ============================================================= #
# ====================== Scheme Settings ====================== #
# ============================================================= #

#scheme: Muse
#scheme: Mist
#scheme: Pisces
scheme: Gemini

darkmode: true


# ============================================================= #
# ================= Site Information Settings ================= #
# ============================================================= #

creative_commons:
  license: by-nc-sa
  size: big
  sidebar: true


# ============================================================= #
# ======================= Menu Settings ======================= #
# ============================================================= #

menu:
  首页: / || fa fa-home
  文章: /archives/ || fa fa-archive
  分类: /categories/ || fa fa-th
  标签: /tags/ || fa fa-tags
  碎碎念: /notes/ || fa fa-comment
  关于: /about/ || fa fa-user

menu_settings:
  icons: true
  badges: false


# ============================================================= #
# ===================== Sidebar Settings ====================== #
# ============================================================= #

sidebar:
  position: left
  display: false
  padding: 20
  offset: 10
  auto_expand: false

avatar:
  url: /images/avatar.jpg
  rounded: true

social:
  GitHub: https://github.com/sunheyi6 || fab fa-github
  Email: shyyouarebest@gmail.com || fa fa-envelope
  RSS: /atom.xml || fa fa-rss

social_icons:
  enable: true
  icons_only: true
  transition: false

toc:
  enable: true
  number: false
  wrap: true


# ============================================================= #
# ====================== Footer Settings ====================== #
# ============================================================= #

footer:
  since: 2014
  icon:
    name: fa fa-heart
    animated: true
    color: "#808080"
  copyright: NexT


# ============================================================= #
# ======================= Post Settings ======================= #
# ============================================================= #

post_meta:
  updated_at:
    enable: true
    another_day: true
  created_at:
    enable: true
    another_day: true

symbols_count_time:
  separated_meta: true
  item_text_total: true

post_edit:
  enable: false
  url: https://github.com/next-theme/theme-next-docs/edit/master/source/


# ============================================================= #
# ==================== Misc Theme Settings ==================== #
# ============================================================= #

mobile_layout_economy: true

codeblock:
  theme:
    light: obsidian
    dark: obsidian
  copy_button:
    enable: true
    style: default

back2top:
  enable: true
  sidebar: false
  scrollpercent: true

github_banner:
  enable: true
  permalink: https://github.com/next-theme/hexo-theme-next
  title: Fork NexT on GitHub

font:
  enable: true
  codes:
    external: true
    family: Inconsolata


# ============================================================= #
# ======================= SEO Settings ======================== #
# ============================================================= #

index_with_subtitle: true

exturl: false

google_site_verification: 5AUIVYTbHIAuz-eQtxSfZbWW5eg9_EVZMSQycIuXrG0


# ============================================================= #
# ======================== Tag Plugins ======================== #
# ============================================================= #

note:
  style: simple
  icons: true
  light_bg_offset: -3

tabs:
  transition:
    tabs: true
    labels: true

mermaid:
  enable: true

wavedrom:
  enable: true


# ============================================================= #
# ==================== External Libraries ===================== #
# ============================================================= #

math:
  mathjax:
    enable: true
    tags: ams

pjax: true

mediumzoom: true

motion:
  enable: false


# ============================================================= #
# =================== Comments and Widgets ==================== #
# ============================================================= #

comments:
  lazyload: true

disqus:
  enable: false
  shortname: next-theme
  count: true


# ============================================================= #
# ================= Statistics and Analytics ================== #
# ============================================================= #

#google_analytics:
  #tracking_id: G-MZXCQSZ8FT


# ============================================================= #
# ====================== Search Services ====================== #
# ============================================================= #

local_search:
  enable: true
  # Show top n results per article, show all results by setting to -1
  top_n_per_article: 1
  # Unescape html strings to the readable one.
  unescape: false
  # Preload the search data when the page loads.
  preload: false


# ============================================================= #
# ======================= CDN Settings ======================== #
# ============================================================= #

vendors:
  internal: cdnjs
  plugins: cdnjs

pace:
  enable: true
  # All available colors:
  # black | blue | green | orange | pink | purple | red | silver | white | yellow
  color: blue
  # All available themes:
  # big-counter | bounce | barber-shop | center-atom | center-circle | center-radar | center-simple
  # corner-indicator | fill-left | flat-top | flash | loading-bar | mac-osx | material | minimal
  theme: minimal

busuanzi_count:
  enable: true
  total_visitors: true
  total_visitors_icon: user
  total_views: true
  total_views_icon: eye
  post_views: true
  post_views_icon: eye

